// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-7-QYazViGRAJco6td-khBnGSb9HTjvs',
    appId: '1:581345291342:web:09b0d313bc2f78bad1e71f',
    messagingSenderId: '581345291342',
    projectId: 'study-sphere-4d387',
    authDomain: 'study-sphere-4d387.firebaseapp.com',
    storageBucket: 'study-sphere-4d387.appspot.com',
    measurementId: 'G-X4YKM8P875',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbQoNrdAEG_4X_87ovFi1YF9KcFJDUqb8',
    appId: '1:581345291342:android:d1ae0a1d9e6a39d8d1e71f',
    messagingSenderId: '581345291342',
    projectId: 'study-sphere-4d387',
    storageBucket: 'study-sphere-4d387.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHTDxE3MGtMZpFzOSj9s2ERi4NlLQ95y0',
    appId: '1:581345291342:ios:48cc49440b530935d1e71f',
    messagingSenderId: '581345291342',
    projectId: 'study-sphere-4d387',
    storageBucket: 'study-sphere-4d387.appspot.com',
    iosBundleId: 'com.example.studysphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHTDxE3MGtMZpFzOSj9s2ERi4NlLQ95y0',
    appId: '1:581345291342:ios:48cc49440b530935d1e71f',
    messagingSenderId: '581345291342',
    projectId: 'study-sphere-4d387',
    storageBucket: 'study-sphere-4d387.appspot.com',
    iosBundleId: 'com.example.studysphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-7-QYazViGRAJco6td-khBnGSb9HTjvs',
    appId: '1:581345291342:web:fa1f936c21553276d1e71f',
    messagingSenderId: '581345291342',
    projectId: 'study-sphere-4d387',
    authDomain: 'study-sphere-4d387.firebaseapp.com',
    storageBucket: 'study-sphere-4d387.appspot.com',
    measurementId: 'G-CJB5N5DWS8',
  );

}